[package]
name = "fuck-node-modules"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.0"
console = "0.15"
dialoguer = "0.10"
humansize = "2.0"
